# Required
version: 2

build:
  os: 'ubuntu-20.04'
  tools:
    python: 'mambaforge-4.10'

# Build documentation in the docs/ directory with Sphinx
sphinx:
  configuration: doc/conf.py

# Optionally set the version of Python and requirements required to build your docs
conda:
    environment: ci/doc.yml

python:
  install:
    - method: pip
      path: .
