name: cf_xarray_test
channels:
  - conda-forge
dependencies:
  - pytest-cov
  - pytest
  - pytest-xdist
  - dask
  - flox
  - lxml
  - matplotlib-base
  - netcdf4
  - pandas
  - pint>=0.18,!=0.24.0
  - pooch
  - regex
  - rich
  - pooch
  - scipy
  - shapely
  - xarray>=2022.03.0
  - pip
  - pip:
      - pytest-pretty
