name: cf_xarray_test
channels:
  - conda-forge
dependencies:
  - pytest-cov
  - pytest
  - pytest-xdist
  - dask
  - flox
  - lxml
  - matplotlib-base
  - netcdf4
  - pandas
  - pint==0.19
  - pooch
  - regex
  - rich
  - pooch
  - scipy
  - shapely
  - xarray==2023.09.0
  - pip
  - pip:
      - pytest-pretty
